### ISSUE TITLE
Is it safe for both LightningStream and PowerDNS to write to the same database file without conflict?

### ISSUE THREAD

**Issue by morningcafe** [PowerDNS/lightningstream#79]
Thank you for your great work. I'm about to apply LightningStream in production, but I have a little concern.

From my understanding, both LightningStream and PowerDNS use the same path to save PowerDNS configuration and its records:
```/lmdb/instance-${instance}/db```
Both need read-write permissions. So, are you implementing some locking in the app to prevent concurrent writes from damaging the file, or do we not need it at all? 
I will run it on Kubernetes with a host path mounted to the pod LS & PDNS. Is that safe enough?

**Comment by joel-ling** [comment]
Hello @morningcafe, Both PowerDNS Authoritative Server and Lightning Stream manipulate and consume data through the [LMDB API](http://www.lmdb.tech/doc/group__mdb.html), which performs concurrency control. (See the [LMDB Main Page](http://www.lmdb.tech/doc/index.html) for more information.)

Since the mechanism involves file locks and related system calls, you would want to make sure the PDNS and LS pods share the same implementation of the C standard library. (For example, Alpine Linux ships `musl` whereas most Linux distros come with `glibc`.) Differences between these libraries in the way they implement file locks have resulted in undefined behaviour, as documented in #75.

**Comment by Habbie** [comment]
Also make sure the PID namespaces of the different containers (if you are using containers) do not overlap.

**Comment by morningcafe** [comment]
@Habbie thank you, I aready read it somewhere, but I don't quite understand it well yet.

On k8s, containers in the same pod have separate PIDs by default, unless we set `shareProcessNamespace: true` , right? From my check, is this all okay?

```
# lightningstream
crictl inspect   --output go-template --template '{{.info.pid}}' eee7b7a65b2be 
2084170
# pdns-auth
crictl inspect   --output go-template --template '{{.info.pid}}' b74bc9c967865
2084204
```
